blueprint:
  name: Collect Bird Buddy Postcard
  description: Collect a Bird Buddy Postcard when a bird visits the feeder.
  domain: automation
  source_url: https://github.com/jhansche/ha-birdbuddy/blob/main/custom_components/birdbuddy/blueprints/collect_postcard.yaml
  author: Joe Hansche
  input:
    feeder_device:
      name: Bird Buddy device
      selector:
        device:
          integration: birdbuddy
    share_media:
      name: Share Media?
      default: true
      selector:
        boolean: {}

mode: single
triggers:
  - trigger: device
    domain: birdbuddy
    device_id: !input feeder_device
    type: new_postcard
actions:
  - alias: Collect a Postcard
    action: birdbuddy.collect_postcard
    data:
      postcard_id: "{{ trigger.event.data.postcard_id }}"
      feeder_id: "{{ trigger.event.data.feeder_id }}"
      share: !input share_media
