name: HACS Action

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  hacs:
    name: HACS validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: hacs/action@main
        with:
          category: integration
